spring:
  application:
    name: springboard-example-web
  profiles:
    active: @profiles.active@
---
spring:
  profiles: development
dubbo:
  registry:
    address: zookeeper://172.18.238.220:2181
rocketmq:
  name-server: 172.18.238.220:9876
  producer:
    group: springboard-example-web
    topic: springboardEventBus
  consumer:
    group: springboard-example-web
    topic: springboardEventBus
server:
  port: 8000